# -*- coding: utf-8 -*-
"""Covid19 Analyzed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gkrZ7DQbpP_hBFX5zAZKqBadTztOv6rG
"""

# Install plotly if not available
!pip install plotly -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

print("✅ Libraries loaded successfully!")

# Load directly from Our World in Data URL
url = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv"
df = pd.read_csv(url)

print(f"Dataset shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")
df.head()

# Select relevant columns
cols = [
    'iso_code', 'continent', 'location', 'date',
    'total_cases', 'new_cases', 'total_deaths', 'new_deaths',
    'total_vaccinations', 'people_vaccinated', 'population'
]
df = df[cols]

# Convert date column
df['date'] = pd.to_datetime(df['date'])

# Drop aggregate regions (continents, World etc.)
df = df[df['continent'].notna()]

# Check missing values
print("Missing values per column:")
print(df.isnull().sum())
print(f"\nCleaned dataset shape: {df.shape}")

# Latest data per country
latest = df.groupby('location').last().reset_index()

# Top 10 countries by total cases
top10_cases = latest.nlargest(10, 'total_cases')[['location','total_cases','total_deaths']]
print("Top 10 Countries by Total Cases:")
print(top10_cases)

# Global totals
print(f"\n Global Total Cases: {latest['total_cases'].sum():,.0f}")
print(f" Global Total Deaths: {latest['total_deaths'].sum():,.0f}")

import plotly.io as pio
pio.renderers.default = 'colab'

# Top 10 countries bar chart
fig = px.bar(
    top10_cases,
    x='location',
    y='total_cases',
    title='Top 10 Countries by Total COVID-19 Cases',
    color='total_cases',
    color_continuous_scale='Reds',
    labels={'total_cases': 'Total Cases', 'location': 'Country'}
)
fig.show()

# Filter Nigeria
nigeria = df[df['location'] == 'Nigeria'].copy()
nigeria = nigeria.fillna(method='ffill')  # forward fill missing values

print(f"Nigeria data: {nigeria.shape[0]} days of records")
print(nigeria[['date','total_cases','total_deaths','total_vaccinations']].tail(10))

fig, axes = plt.subplots(3, 1, figsize=(10, 12))

# Total Cases over time
axes[0].plot(nigeria['date'], nigeria['total_cases'], color='blue')
axes[0].set_title('Nigeria - Total COVID-19 Cases Over Time')
axes[0].set_ylabel('Total Cases')

# Total Deaths over time
axes[1].plot(nigeria['date'], nigeria['total_deaths'], color='red')
axes[1].set_title('Nigeria - Total Deaths Over Time')
axes[1].set_ylabel('Total Deaths')

# Vaccinations over time
axes[2].plot(nigeria['date'], nigeria['total_vaccinations'], color='green')
axes[2].set_title('Nigeria - Total Vaccinations Over Time')
axes[2].set_ylabel('Total Vaccinations')

plt.tight_layout()
plt.savefig('nigeria_covid_analysis.png', dpi=150)
plt.show()
print("✅ Chart saved!")

# Prepare data for ML
nigeria_ml = nigeria[['date', 'total_cases']].dropna().copy()
nigeria_ml['days'] = (nigeria_ml['date'] - nigeria_ml['date'].min()).dt.days

X = nigeria_ml[['days']]
y = nigeria_ml['total_cases']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
    )

    # Train Linear Regression
model = LinearRegression()
model.fit(X_train, y_train)

    # Evaluate
y_pred = model.predict(X_test)
print(f"R² Score: {r2_score(y_test, y_pred):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):,.0f}")

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

# Prepare data
nigeria_ml = nigeria[['date', 'total_cases']].dropna().copy()
nigeria_ml['days'] = (nigeria_ml['date'] - nigeria_ml['date'].min()).dt.days

X = nigeria_ml[['days']]
y = nigeria_ml['total_cases']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Try degrees 2, 3, 4 and pick best
best_r2 = 0
best_degree = 2
best_model = None

for degree in [2, 3, 4]:
    model = make_pipeline(PolynomialFeatures(degree), LinearRegression())
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    print(f"Degree {degree} → R²: {r2:.4f} | RMSE: {rmse:,.0f}")

    if r2 > best_r2:
        best_r2 = r2
        best_degree = degree
        best_model = model

print(f"\n✅ Best Degree: {best_degree} | Best R²: {best_r2:.4f}")

# Predict next 90 days with best model
last_day = nigeria_ml['days'].max()
future_days = np.array(range(last_day+1, last_day+91)).reshape(-1,1)
future_preds = best_model.predict(future_days)

# Actual vs Predicted on test set
y_pred_test = best_model.predict(X_test)

# Plot
plt.figure(figsize=(10,5))
plt.plot(nigeria_ml['days'], nigeria_ml['total_cases'],
         label='Actual', color='blue')
plt.plot(future_days, future_preds,
         label=f'Predicted - Degree {best_degree} (next 90 days)',
         color='orange', linestyle='--')
plt.title(f'Nigeria COVID-19 - Polynomial Regression (Degree {best_degree})')
plt.xlabel('Days since first case')
plt.ylabel('Total Cases')
plt.legend()
plt.tight_layout()
plt.savefig('nigeria_poly_prediction.png', dpi=150)
plt.show()
print("✅ Polynomial prediction chart saved!")